Lesson 4
pirozhok1985/Csharp_2 pull request #4
Opened 2021-01-28 15:22 UTC by pirozhok1985

Успех. Не понял как Использвать predicate в orderby, ведь один возвращает bool, а второму нужен ключ для сортировки

2021-02-01 15:49 UTC, Infarh requested changes

2021-02-01 15:49 UTC, Infarh commented on Lesson_1/HomeWork_1/Game.cs
> +        public static string __authorName { get; private set; }
Имена свойств должны отличаться от имён полей! Свойства пишем с большой буквы, поля - с большой буквы предваряя имя символами подчёркивания.

2021-02-01 15:49 UTC, Infarh commented on Lesson_1/HomeWork_1/Game.cs
> +            if ((Height | Width) > 1000 | (Height | Width) < 0) { throw new SplashScreenException("Upps! Sorry, this is not allowed!", DateTime.Now); }
Ерунда получается: "если результат операции `побистовое_или` двух значений `Height`, `Width` > 1000, или если результат операции `побистовое_или` двух значений `Height`, `Width` < 0, то это ошибка". С точки зрения логики программы - это бред. Напишите влоб: `Height > 1000 | Width > 1000 | Height < 0 | Width < 0`. Операция "побитовое или" ВАм тут явно не нужна!

2021-02-01 15:49 UTC, Infarh commented on Lesson_2/Lesson_2/HomeWork_2_Lesson_4/Program.cs
> +                    Pairs.Add(list[i],count);
count? Почему не просто 1?

2021-02-02 00:38 UTC, pirozhok1985 commented on Lesson_1/HomeWork_1/Game.cs
> +        public static string __authorName { get; private set; }
Поправил, спасибо.

2021-02-02 00:39 UTC, pirozhok1985 commented on Lesson_1/HomeWork_1/Game.cs
> +            if ((Height | Width) > 1000 | (Height | Width) < 0) { throw new SplashScreenException("Upps! Sorry, this is not allowed!", DateTime.Now); }
Сам себя обдурил, называется. Поправил.

2021-02-02 00:40 UTC, pirozhok1985 commented on Lesson_2/Lesson_2/HomeWork_2_Lesson_4/Program.cs
> +                    Pairs.Add(list[i],count);
Хотел себя проверить, если ошибка в логике, то count это покажет. Поправил. Спасибо огромное за code review!

2021-02-02 00:41 UTC, pirozhok1985 commented
73fef534a8849f84d9fabdaf56491eb7f15412b8 - устранил замечания

2021-02-02 00:51 UTC, merged